name: Create Buzz Cut PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: kotaoue/pr-checklist-collector@v1
        with:
          checks: |
            0mm
            1mm
            2mm
            3mm
            4mm
            5mm
          output_file: results/{yyyy-mm-dd}.json
          assignee: kotaoue
